server {
  listen 80;
  # proxy all API requests to the app (Laravel API on :8000)
  location / {
    proxy_pass         http://application:8000;
    proxy_set_header   Host              $host;
    proxy_set_header   X-Forwarded-Proto $scheme;
    proxy_set_header   X-Forwarded-For   $remote_addr;
    proxy_http_version 1.1;
    proxy_set_header   Connection        "";
    proxy_read_timeout 300;
  }
}
